# Generated by Django

from django.db import migrations
import uuid

def create_unique_skus(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    for product in Product.objects.all():
        if not hasattr(product, 'sku') or not product.sku:
            product.sku = f"SKU-{uuid.uuid4().hex[:8].upper()}"
            product.save()

def reverse_create_unique_skus(apps, schema_editor):
    # No reverse operation needed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_session_key_cart_updated_at_category_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(create_unique_skus, reverse_create_unique_skus),
    ]
